### ISSUE TITLE
Include created, published, or modified dateTimes

### ISSUE THREAD

**Issue by csarven** [solid/solid-oidc#105]

**Comment by acoburn** [comment]
Please provide guidance on a suitable "created" date: 

* The original [WebID-OIDC](https://github.com/solid/webid-oidc-spec) document is from 2017
* That text was imported into the Authentication Panel in Dec 2019
* The text here was imported from the Authentication Panel in July 2021

I would suggest that a created date should align with the FPWD, namely March 28, 2022
Published date is auto-generated by bikeshed and is already part of anything submitted to `solid/specification`
And modified date will be the same as published for anything in /TR. For editor's drafts, modified dates are already presented.

**Comment by csarven** [comment]
That works.

At least one or both of Created and Published should be present. Modified should be present.

Some examples below. Not very exciting for the initial publication:

TR/oidc
* Created: 2022-03-28 (when this resource start to exist with a representation.. we can merge PRs on the intended created date or thereabouts - no big deal on the precision IMO until the publication mechanics are smoothed out)
* Published: 2022-03-28 (usually same as created but can be after - could've been due to whenever it got listed under TR/ or announced/publicised in some other way, e.g., feed)
* Modified: 2022-03-28 (same as created)

TR/2021/oidc-20220328
* Created: 2022-03-28 (whenever it came to existence)
* Published: 2022-03-28 (usually same as created...)
* Modified: 2022-03-28 (under normal circumstances this resource is deemed to be immutable but things do change. stick to created)

When a new version is available e.g.:

TR/oidc
* Created: 2022-03-28 (don't change)
* Published: 2022-03-28 (don't change)
* Modified: 2022-04-30 (we update because the document's contents changed)

TR/2022/oidc-20220430
* Created: 2022-04-30 (same as other snapshots)
* Published: 2022-04-30 (same as other snapshots)
* Modified: 2022-04-30 (same as other snapshots)

And for ED (example path):

ED/oidc
* Created: 2021-07-16 (whenever it came to existence)
* Published: 2021-07-16 (usually same as created...)
* Modified: 2022-04-30 (update as you go)

Note that above I used the date from gh-page's first commit - assuming everything else was configured for https://solid.github.io/solid-oidc/
