### ISSUE TITLE
Update spec URL and document status in solid-oidc

### ISSUE THREAD

**Issue by csarven** [solid/solid-oidc#11]
In /index.bs and /primer/index.bs

Update spec URLs... eg /specification/solid-oidc to /solid-oidc

For Status of this Document, revise from https://github.com/solid/specification/blob/e14c6385533b975d83cc9250aedd242965cbdad9/protocol.html#L207 (Editor's Draft) or nearly identical: https://github.com/solid/specification/blob/cd8fbb1d8298e7064b444418e7c737f42fe4ef3e/wac.html#L278 (Draft).

**Comment by acoburn** [comment]
Resolved via #14 and #15
