### ISSUE TITLE
Migrate solid-oidc issues from authentication-panel

### ISSUE THREAD

**Issue by csarven** [solid/solid-oidc#12]
.. issues that can be clearly separated. Leave general discussions, comparisons etc..

**Comment by matthieubosquet** [comment]
Non-exhaustive list of issues candidate for migration:
https://github.com/solid/authentication-panel/issues/181; https://github.com/solid/authentication-panel/issues/86; https://github.com/solid/authentication-panel/issues/146

**Comment by acoburn** [comment]
I have moved all the issues that were clearly Solid-OIDC, so I'll mark this as closed. If there are other issues to move, please let me know
