### ISSUE TITLE
Solid OIDC Client ID Document

### ISSUE THREAD

**Issue by csarven** [solid/solid-oidc#122]
In #clientids-document:

>This example uses JSON-LD for the Client ID Document:

Mention JSON-LD version if relevant or link to https://www.w3.org/TR/json-ld/ instead.

https://openid.net/specs/openid-connect-core-1_0.html uses `response_type`. http://www.w3.org/ns/solid/oidc#response_types and #example-9e406e39 uses `response_types`. Is that intended or typo?

**Comment by acoburn** [comment]
`response_types` is correct.

Please see https://openid.net/specs/openid-connect-registration-1_0.html#ClientMetadata
