### ISSUE TITLE
Document and update prior spec references

### ISSUE THREAD

**Issue by csarven** [solid/solid-oidc#13]
Across repos that are under the solid org.. for both solid-oidc and its primer

For https://solid.github.io/authentication-panel/solid-oidc/

* [x] https://solidproject.org/TR/protocol

**Comment by acoburn** [comment]
https://github.com/solid/specification/pull/293

**Comment by acoburn** [comment]
See also https://github.com/solid/authentication-panel/pull/183

**Comment by acoburn** [comment]
This is complete
