### ISSUE TITLE
Require "webid" scope for OIDC Dynamic Client Registration

### ISSUE THREAD

**Issue by dteleguin** [solid/solid-oidc#168]
Solid-OIDC clients need a very special handling within the OP, as opposed to pure OIDC ones:
* PKCE must be enforced (auth + token endpoints);
* DPoP must be enforced (token endpoint);
* DPoP-bound ID token must be issued (token endpoint; Solid-specific feature);
* clients must be marked for automatic expiration and purging (see #167).

This is not a problem with Solid-only OPs. But when implementing Solid-OIDC support on top of generic OIDC OPs (e.g. Keycloak), we need a mechanism to allow OP to clearly distinguish between Solid-OIDC and pure OIDC clients. In its turn, this is not a problem with the clients registered on the fly via a Client ID doc (they are by default Solid-OIDC). But when it comes to the clients registered via DCR, there is no way for the OP to determine the nature of the client.

I'd suggest that we make the `scope` field mandatory for DCR requests, and require it to contain the `webid` value. This will allow OPs to mark the client thus registered as a Solid-OIDC compliant one:

```json
{
  "client_name": "S-C-A Browser Demo Client App",
  "application_type": "web",
  "redirect_uris": [
    "https://solid-client-authn-js.vercel.app/demo/"
  ],
  "subject_type": "pairwise",
  "token_endpoint_auth_method": "client_secret_basic",
  "scope" : "openid profile offline_access webid" // <---
}
```

I also suggest that we add an example of such a call to Section 5.2, similar to Section 5.1.

**Comment by elf-pavlik** [comment]
Thank you @dteleguin!

I'll prepare a PR following your suggestion.
