### ISSUE TITLE
Update authentication-panel gh pages

### ISSUE THREAD

**Issue by csarven** [solid/solid-oidc#21]
https://github.com/solid/solid-oidc/issues/13 aims to remove/update references where possible, however there may still be references to authentication-panel's gh pages. So:

Since authentication-panel's gh pages for solid-oidc and primer are no longer needed, remove its content and, if possible, set a redirect to solid-oidc's gh pages.

**Comment by acoburn** [comment]
See https://github.com/solid/authentication-panel/pull/183
