### ISSUE TITLE
Mistakes in the 12th step of the Request flow in the Solid-OIDC Primer

### ISSUE THREAD

**Issue by lecoqlibre** [solid/solid-oidc#229]
The [step 12](https://solidproject.org/TR/oidc-primer#request-flow-step-12) of the Request Flow seems to be mistaken.

Indeed, [the description](https://solidproject.org/TR/oidc-primer#request-flow-step-12) starts by saying "Using the kid value in the ID token" but there is no such kid value in the ID token (body). Should not it be in the "ID token header" instead?

The title on [the diagram](https://solidproject.org/TR/oidc-primer#request-flow) talk about verifying the access token but should not it be about verifying the ID token instead?

Should I make a PR?

**Comment by elf-pavlik** [comment]
> Indeed, [the description](https://solidproject.org/TR/oidc-primer#request-flow-step-12) starts by saying "Using the kid value in the ID token" but there is no such kid value in the ID token (body). Should not it be in the "ID token header" instead?

The current text doesn't specify payload or header, I think it assumes that one will refer to JWS spec for those details.
I'm wondering if we should add `kid` to the snippet in [19. Generates the id_token](https://solidproject.org/TR/oidc-primer#authorization-code-pkce-flow-step-19). Matching the `kid` from [11. Requests JWKS](https://solidproject.org/TR/oidc-primer#request-flow-step-11)

> The title on [the diagram](https://solidproject.org/TR/oidc-primer#request-flow) talk about verifying the access token but should not it be about verifying the ID token instead?

You are right, the note in the diagram needs to be corrected.

> Should I make a PR?

Yes! Please

**Comment by lecoqlibre** [comment]
> The current text doesn't specify payload or header, I think it assumes that one will refer to JWS spec for those details.

Ok we could maybe add a link to this specification?

> I'm wondering if we should add kid to the snippet in [19. Generates the id_token](https://solidproject.org/TR/oidc-primer#authorization-code-pkce-flow-step-19). Matching the kid from [11. Requests JWKS](https://solidproject.org/TR/oidc-primer#request-flow-step-11)

I think that it can help as I looked exactly at this when reading the primer to try to implement. And the two steps do refer to the same user (Alice) and OP (https://secureauth.example).

**Comment by elf-pavlik** [comment]
fixed in #230
