### ISSUE TITLE
specify parameters in WWW-Authenticate header

### ISSUE THREAD

**Issue by elf-pavlik** [solid/solid-oidc#25]
Currently spec only mentions in non-normative Basic Flow section:

> The RS returns a 401 with a WWW-Authenticate HTTP header containing parameters that inform the Client that a DPoP-bound Access Token is required.

I think this should go along with claim in access token (related to claim in id_token solid/authentication-panel#146)

**Comment by elf-pavlik** [comment]
DPoP mentions some requirements https://www.ietf.org/archive/id/draft-ietf-oauth-dpop-03.html#section-7.1

**Comment by elf-pavlik** [comment]
After reviewing DPoP draft and considering that we are adding `webid` scope. I think the following should be sufficient:

```http
HTTP/1.1 401 Unauthorized
 WWW-Authenticate: DPoP scope="webid", algs="ES256 PS256"
```

Keeping in mind #18 we probably would just need to add `as_uri="<URI of Authorization Server>"` and possibly remove the scope. 

While I believe we should move in direction of removing Access Token issued by OP, until then we might add a requirement on `webid` scope in that token for consistency.

**Comment by elf-pavlik** [comment]
We should also add examples of using multiple `WWW-Authenticate` headed or a single one with multiple challenges.

**Comment by elf-pavlik** [comment]
We should consider `as_uri` parameters with other schemes, for example GNAP.

**Comment by acoburn** [comment]
@elf-pavlik do you feel that this issue has been resolved now that we have https://solid.github.io/solid-oidc/#authorization-server-discovery
