### ISSUE TITLE
Determine identifier and title for the solid-oidc spec

### ISSUE THREAD

**Issue by csarven** [solid/solid-oidc#27]
Current identifier `solid-oidc` and title "SOLID-OIDC"

To be requested at https://github.com/solid/solidproject.org/ . The spec will eventually be under `https://solidproject.org/TR/{id}`

(see also https://github.com/solid/solidproject.org/issues/249 )

TODO

* [x] change spec URL in bikeshed head
* [x] change URL in discovery added in solid/authentication-panel#119

**Comment by acoburn** [comment]
The related tasks are complete
