### ISSUE TITLE
Adjust GitHub repository settings

### ISSUE THREAD

**Issue by matthieubosquet** [solid/solid-oidc#3]
It would be good to review the settings, gate PRs to main and disable direct pushes.

See also: https://github.com/solid/solid-oidc/pull/1#issuecomment-881477176, https://gitter.im/solid/authentication-panel?at=60f19c1df1274d5e5050d346

Small related ammendment to CI: https://github.com/solid/solid-oidc/pull/2

cc @csarven

**Comment by acoburn** [comment]
I have been able to adjust some of the settings, such that we are now publishing the editors' draft at https://solid.github.io/solid-oidc/

I am not able to adjust the branch protection rules

**Comment by csarven** [comment]
Updated. Added @matthieubosquet as a maintainer.

Unless there is anything incorrect or outstanding, this Issue can be closed.

**Comment by matthieubosquet** [comment]
As a maintainer, I can't update the repository's settings.

**Comment by acoburn** [comment]
The settings are now quite workable, so I am going to close this.
