### ISSUE TITLE
Clarifying specific areas of overlap with AuthZ

### ISSUE THREAD

**Issue by elf-pavlik** [solid/solid-oidc#30]
We discussed couple of times areas possibly overlapping with AuthZ. I'd like to start documenting them in this issue. I think currently we can point out:

* Use of `WWW-Authenticate` HTTP header in response from RS (for example [UMA2.0 includes link to Authorization Server](https://docs.kantarainitiative.org/uma/wg/rec-oauth-uma-grant-2.0.html#permission-success-to-client))
* Use of `Authorization` HTTP header by the client (most likely Access Token - see next point)
* Contents of Access Token (currently only used to signal WebID, may need to include notion of scopes. related work [OAuth 2.0 Rich Authorization Request](https://tools.ietf.org/html/draft-lodderstedt-oauth-rar-03) influencing GNAP, [Solid Interop Data Grants](https://solid.github.io/data-interoperability-panel/specification/#datamodel-data-grant), [ZCAP-LD Caveats](https://w3c-ccg.github.io/zcap-ld/#caveats)).
* Signaling authorization related requirements by RS (or RS associated AS), for example expected credentials. (this on is very much about AuthZ but may impact which party client needs to present credentials to RS or AS hinted by RS.

**Comment by elf-pavlik** [comment]
#18 starts addressing this issue

**Comment by acoburn** [comment]
@elf-pavlik do you feel that this issue has been resolved or is there more to address here?
