### ISSUE TITLE
Clarify implicitly trusted OIDC issuer

### ISSUE THREAD

**Issue by RubenVerborgh** [solid/solid-oidc#51]
From a discussion with @timbl, we gathered that the old mechanism to implicitly trust OIDC issuers was as follows:
- If your WebID is `https://timbl.solidcommunity.net/profile/card#me`, then the following issuers are implicitly trusted:
  - `https://timbl.solidcommunity.net/`
  - `https://solidcommunity.net/`

However, the specification text currently reads:

> The user’s WebID in the webid claim MUST be dereferenced and checked against the iss claim in the Access Token. If the iss claim is different from the domain of the WebID, then the RS MUST check the WebID document for the existence of a statement matching `?webid <http://www.w3.org/ns/solid/terms#oidcIssuer> ?iss.`, where ?webid and ?iss are the values of the webid and iss claims respectively. 

And I have a couple of questions/issues surrounding this:

1. Why MUST the WebID always be dereferenced, even if the `iss` claim matches the domain of the WebID?
    - Nothing is done with the resulting information in that case, but is this to guarantee that the profile is publicly available?
    - If so, why?
2. The current language is ambiguous. It states that "if the `iss` claim is different from the domain of the WebID", but this precondition will _always_ fail if taken literally.
    - For example, for the WebID `https://example.org/profile/card#me`, the domain is `example.org`. However, the `iss` claim from that website is likely to be something like `https://example.org`, and hence will not [string] match.
    - Do we mean that the _domain_ of the WebID should be the same as the _domain_ of the `iss` claim?
    - Do the port numbers have to be the same as well?
    - Does the protocol have to be the same as well?
    - Do we accept both `https://example.org` and `https://example.org/` (with slash)?
    - Do we accept an `iss` of `https://example.org/arbitrary/path`, which does have the same domain?
3. Apart from the ambiguity, the old mechanism's behavior was to also trust parent domains. So if the WebID was on a subdomain, then it's parent domain(s) would be trusted as well. Is this desired behavior or not.

**Comment by elf-pavlik** [comment]
During the call yesterday @acoburn suggested the even if WebID Document is not public, HTTP response could still include OIDC Issuer delegation in Link Header. Currently, we have it defined as an optional way of advertising it but we could consider making it required if the document itself is not public.

@jeff-zucker I think it would be great to consider implications of WebID Document not being public in the Task Force working standards predicates used there. Personally, I would lean in the direction to require it to be public and provide a clear way how to extend it with non-public information. I would prefer not to dive into that too deep here and discuss it wherever the Task Force focused on WebID Document will work.

**Comment by csarven** [comment]
Lower level: https://github.com/w3c/WebID/issues/1

**Comment by elf-pavlik** [comment]
In case when the user makes their WebID profile private. Unless we provide explicit `solid:oidcIssuer` delegation in Link Header, the User would need to provide the URL of their OP/Issuer to the Client. Otherwise, the Client wouldn't be able to discover OP/Issuer based on the User's WebID.

**Comment by matthieubosquet** [comment]
To be considered maybe is the fact that (in my understanding):
1. The existence of a WebID is justified by it being used to assert control over a URI and therefore the data used to assert such control by nature doesn't seem to be private (OIDC issuer/public key...);
2. There is no restrictions about WebIDs forbidding anyone to link them to any number of public and/or private profile documents.

See also a detailed example: https://github.com/w3c/WebID/issues/1#issuecomment-977326427

**Comment by matthieubosquet** [comment]
Also, I'm not an expert, but I can imagine that there are cases where someone wouldn't want to trust an issuer on the same domain as their WebID or even subdomain. I am therefore against implicit trust, it doesn't seem to solve any technical issues and introduces security concerns, sounds like a bag of crabs to me.

**Comment by elf-pavlik** [comment]
#80 captures discussed specific case where WebID Document wouldn't be public

#79 will remove any notion of implicit trust and links to #80 inline

Can we close this issue?
