### ISSUE TITLE
Document claims_supported field

### ISSUE THREAD

**Issue by michielbdejong** [solid/solid-oidc#56]
According to https://github.com/solid/solid-oidc-tests/blob/defd6a2/data/solid-oidc.jsonld#L97
"The server metadata MUST indicate support for the webid claim in the claims_supported field."
The source given for this is https://solid.github.io/solid-oidc/#discovery but when you read that paragraph, the information about claims_supported is missing.

Note that https://openid.net/specs/openid-connect-discovery-1_0.html#ProviderMetadata only prescribes claims_supported as "recommended", not as "MUST".

In either case, it makes sense to document this requirement at the solid-oidc spec level.

**Comment by acoburn** [comment]
> The server metadata MUST indicate support for the webid claim in the claims_supported field.

The error is that `claims_supported` is recommended, not required by OpenID Connect. Therefore, it is recommended, not required by Solid-OIDC. The test suite should be adjusted to be clear about that, i.e., _if_ the `claims_supported` property is present, then check whether `webid` is present.

**Comment by acoburn** [comment]
In terms of documentation, unless Solid-OIDC changes the requirement level (i.e. recommended -> required), there is no need to restate what is already part of OpenID connect. It _could_ however, be described in the Solid-OIDC Primer.

**Comment by acoburn** [comment]
See https://github.com/solid/solid-oidc-tests/commit/18b2b7100f421767b2d5ee8185316a8b8a242fc0

The corresponding test checks for a `webid` value in a `claims_supported` array at the "Recommended" level per https://openid.net/specs/openid-connect-discovery-1_0.html#ProviderMetadata

**Comment by acoburn** [comment]
This issue has been addressed in the Solid-OIDC test suite and no further discussion has occurred. I am marking this as resolved.
