### ISSUE TITLE
Clarification of exp claim in DPoP Access Token

### ISSUE THREAD

**Issue by BarracudaX** [solid/solid-oidc#61]
I think specification lacks clarification of exp claim which currently is defined as "The expiration claim is the time at which the DPoP-bound Access Token becomes invalid.". I assume exp is similar to openID connect exp claim, which is defined as "Its value is a JSON number representing the number of seconds from 1970-01-01T0:0:0Z as measured in UTC until the date/time."
Also iat needs clarification.

**Comment by acoburn** [comment]
The `exp` and `iat` claims come from OpenID Connect. This specification does not change the meaning of these claims and therefore has no need to make any statements about them.
