### ISSUE TITLE
consider using uma_profiles_supported

### ISSUE THREAD

**Issue by elf-pavlik** [solid/solid-oidc#63]
This issue tracks suggestion from PR https://github.com/solid/solid-oidc/pull/18#discussion_r772442817

https://docs.kantarainitiative.org/uma/wg/rec-oauth-uma-grant-2.0.html#rfc.section.2

> uma_profiles_supported
>
 >   OPTIONAL. UMA profiles and extensions supported by this authorization server. The value is an array of string values, where each string value is a URI identifying an UMA profile or extension. As discussed in Section 4, an authorization server supporting a profile or extension related to UMA SHOULD supply the specification's identifying URI (if any) here.

**Comment by acoburn** [comment]
Now that the Solid-OIDC draft contains https://solid.github.io/solid-oidc/#obtaining-access-token, can this issue be marked as resolved?

**Comment by elf-pavlik** [comment]
Thank you @acoburn
