### ISSUE TITLE
WebID spec is not explicitly linked

### ISSUE THREAD

**Issue by RubenVerborgh** [solid/solid-oidc#71]
https://solid.github.io/solid-oidc/ references WebID but, in contrast to https://solidproject.org/TR/protocol, does not link to https://www.w3.org/2005/Incubator/webid/spec/identity/

This is relevant for issues such as https://github.com/solid/specification/issues/376

**Comment by acoburn** [comment]
How is WebID not linked? See the [terminology](https://solid.github.io/solid-oidc/#terms) section as well as the 
 specific bibliography section: https://solid.github.io/solid-oidc/#biblio-webid

Is there a particular section you see this link missing?

**Comment by RubenVerborgh** [comment]
I apologize; I had taken the statement

> In line with Linked Data principles, a WebID is a HTTP URI that, when dereferenced, resolves to a profile document that is structured data in an RDF 1.1 format. 

from a non-normative section, where the concept is not linked. (But yes, non-normative.)

So this one can be closed for me; but solid/specification#376 might still be an issue.

**Comment by RubenVerborgh** [comment]
Although we might also want explicit references in `8.4. OIDC ID Token Validation`.
