### ISSUE TITLE
Clarification webid claim in idtoken

### ISSUE THREAD

**Issue by wdantuma** [solid/solid-oidc#74]
Reading the specification and primer it is unclear to me how the OP can present the same webid claim as the webid presented by the user to the client. What am i missing ? From what i see the only place where it can be transferred is during the authorization or token request. An other option i think would be that the webid is also stored at the OP but how is assured that it is the same as presented at the client ?

**Comment by elf-pavlik** [comment]
End-user has to be authenticated with OP, details are out of scope for Solid-OIDC. OP has to know what is the WebID of the currently authenticated user. This association happens at account creation time when also a way to authenticate with OP gets established.

If OP allows the association of multiple WebID with a single user account (specific to that OP) they need to provide a way for the user to select which WebID they want to use, this would be part of the prompt they show to the user.

Either way association of WebID with a user account (specific to the OP) happens before the Solid-OIDC flow .

**Comment by wdantuma** [comment]
> This level of validation is something that a client could do today.
>
>In fact, I would argue that it would be a good practice for apps to inform the user which account they are using. But that would be more in the domain of best practices than normative requirements.

@acoburn thanks

Agreed, both, setting the webid claim in the DPop header and validating the webid claim in the IdToken would be the responsibility of the client i guess.

**Comment by acoburn** [comment]
> setting the webid claim in the DPop header

Doing this does not materially contribute to the security of the exchange between client and server, and I would not recommend it.

The ID token will already be bound to the DPoP keypair (via the `cnf` claim) and the DPoP proof will be bound to the ID token via the `ath` claim. Reiterating a `webid` claim in the DPoP proof would only be redundant.

**Comment by wdantuma** [comment]
> Doing this does not materially contribute to the security of the exchange between client and server

Agreed, closing the issue
