### ISSUE TITLE
URIs for ED and CG-DRAFT

### ISSUE THREAD

**Issue by csarven** [solid/solid-oidc#98]
The identity of the resource https://solid.github.io/solid-oidc/ was known previously known as the ED. The same URI is now used for CG-CRAFT (re https://github.com/solid/solid-oidc/pull/97 ). This is known as a URI collision as per AWWW.

I may have missed the plans/discussion about this, so would appreciate any pointers: Will ED seize to exist going forward or will it be available under a different URI? Will CG-DRAFT be a living document of sorts - acting a bit like ED?

**Comment by elf-pavlik** [comment]
I think we could manage it in the following way:

* https://solid.github.io/solid-oidc/ will stay as ED
* https://solidproject.org/TR/solid-oidc would act as the latest CG-DRAFT
* https://solidproject.org/TR/2022/solid-oidc-{tag} would act as a snapshot of each CG-DRAFT

Most likely we would need to revert #97 and make it a part of taking a snapshot of ED.
I'm happy to help with automating things using GitHub workflow. We just need to document the required steps first.

**Comment by acoburn** [comment]
I have no opinions on this -- whatever is most sensible to manage. Having just gone through the process of moving the current draft into the /specification repo, I would be very interested in finding ways to make that process easier and less error-prone. Currently, the process involves a number of manual file renames, etc.

**Comment by elf-pavlik** [comment]
@acoburn could you write down the required steps so we all have a better understanding of how this manual path works today?

**Comment by acoburn** [comment]
What I would prefer to do is express the changes in terms of a GH Action so that we don't need to manually perform them each time

**Comment by acoburn** [comment]
We now have automation (and [documentation](https://github.com/solid/solid-oidc#releasing-a-new-solid-oidc-draft-report)) for performing these changes.

**Comment by elf-pavlik** [comment]
We should keep an eye on https://github.com/solid/specification/issues/370 for when the deployment strategy to solidproject.org changes.

@csarven do you see anything else that needs to be addressed in this issue?

**Comment by csarven** [comment]
If https://solid.github.io/solid-oidc/ remains as ED, good. The rest can work out in parallel.
